# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1, verbose_name='订单状态'),
        ),
    ]
